it('selects from dropdown', () => {
  cy.visit('http://localhost:3000')
  // cy.get('#circleDown').click()
    // .type('Teacher{enter}')
  cy.get('[data-cy=parent] > li > a').click({force:true})
  cy.get('#Email')
    .type('maggie@maggie.com')
  cy.get('#password')
    .type('m')
  cy.get('.loginForm > span > .btn').click() 
  cy.url().should('eq', 'http://localhost:3000/parents') 
})